use device_query::Keycode;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

// Plain duplicates from device_query crate (only add Serialize/Deserialize)
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize, TS, Debug)]
pub enum LocalKeycode {
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    Escape,
    Space,
    LControl,
    RControl,
    LShift,
    RShift,
    LAlt,
    RAlt,
    Command,
    RCommand,
    LOption,
    ROption,
    LMeta,
    RMeta,
    Enter,
    Up,
    Down,
    Left,
    Right,
    Backspace,
    CapsLock,
    Tab,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,

    // Numpad keys which have not been implemented: NumpadSeparator NumLock
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadSubtract,
    NumpadAdd,
    NumpadDivide,
    NumpadMultiply,
    NumpadEquals,
    NumpadEnter,
    NumpadDecimal,

    // The following keys names represent the position of the key in a US keyboard,
    // not the sign value. In a different keyboards and OS, the position can vary.
    Grave,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
}

impl From<Keycode> for LocalKeycode{
    fn from(value: Keycode) -> Self {
        match value {
            Keycode::Key0 => LocalKeycode::Key0,
            Keycode::Key1 => LocalKeycode::Key1,
            Keycode::Key2 => LocalKeycode::Key2,
            Keycode::Key3 => LocalKeycode::Key3,
            Keycode::Key4 => LocalKeycode::Key4,
            Keycode::Key5 => LocalKeycode::Key5,
            Keycode::Key6 => LocalKeycode::Key6,
            Keycode::Key7 => LocalKeycode::Key7,
            Keycode::Key8 => LocalKeycode::Key8,
            Keycode::Key9 => LocalKeycode::Key9,
            Keycode::A => LocalKeycode::A,
            Keycode::B => LocalKeycode::B,
            Keycode::C => LocalKeycode::C,
            Keycode::D => LocalKeycode::D,
            Keycode::E => LocalKeycode::E,
            Keycode::F => LocalKeycode::F,
            Keycode::G => LocalKeycode::G,
            Keycode::H => LocalKeycode::H,
            Keycode::I => LocalKeycode::I,
            Keycode::J => LocalKeycode::J,
            Keycode::K => LocalKeycode::K,
            Keycode::L => LocalKeycode::L,
            Keycode::M => LocalKeycode::M,
            Keycode::N => LocalKeycode::N,
            Keycode::O => LocalKeycode::O,
            Keycode::P => LocalKeycode::P,
            Keycode::Q => LocalKeycode::Q,
            Keycode::R => LocalKeycode::R,
            Keycode::S => LocalKeycode::S,
            Keycode::T => LocalKeycode::T,
            Keycode::U => LocalKeycode::U,
            Keycode::V => LocalKeycode::V,
            Keycode::W => LocalKeycode::W,
            Keycode::X => LocalKeycode::X,
            Keycode::Y => LocalKeycode::Y,
            Keycode::Z => LocalKeycode::Z,
            Keycode::F1 => LocalKeycode::F1,
            Keycode::F2 => LocalKeycode::F2,
            Keycode::F3 => LocalKeycode::F3,
            Keycode::F4 => LocalKeycode::F4,
            Keycode::F5 => LocalKeycode::F5,
            Keycode::F6 => LocalKeycode::F6,
            Keycode::F7 => LocalKeycode::F7,
            Keycode::F8 => LocalKeycode::F8,
            Keycode::F9 => LocalKeycode::F9,
            Keycode::F10 => LocalKeycode::F10,
            Keycode::F11 => LocalKeycode::F11,
            Keycode::F12 => LocalKeycode::F12,
            Keycode::F13 => LocalKeycode::F13,
            Keycode::F14 => LocalKeycode::F14,
            Keycode::F15 => LocalKeycode::F15,
            Keycode::F16 => LocalKeycode::F16,
            Keycode::F17 => LocalKeycode::F17,
            Keycode::F18 => LocalKeycode::F18,
            Keycode::F19 => LocalKeycode::F19,
            Keycode::F20 => LocalKeycode::F20,
            Keycode::Escape => LocalKeycode::Escape,
            Keycode::Space => LocalKeycode::Space,
            Keycode::LControl => LocalKeycode::LControl,
            Keycode::RControl => LocalKeycode::RControl,
            Keycode::LShift => LocalKeycode::LShift,
            Keycode::RShift => LocalKeycode::RShift,
            Keycode::LAlt => LocalKeycode::LAlt,
            Keycode::RAlt => LocalKeycode::RAlt,
            Keycode::Command => LocalKeycode::Command,
            Keycode::RCommand => LocalKeycode::RCommand,
            Keycode::LOption => LocalKeycode::LOption,
            Keycode::ROption => LocalKeycode::ROption,
            Keycode::LMeta => LocalKeycode::LMeta,
            Keycode::RMeta => LocalKeycode::RMeta,
            Keycode::Enter => LocalKeycode::Enter,
            Keycode::Up => LocalKeycode::Up,
            Keycode::Down => LocalKeycode::Down,
            Keycode::Left => LocalKeycode::Left,
            Keycode::Right => LocalKeycode::Right,
            Keycode::Backspace => LocalKeycode::Backspace,
            Keycode::CapsLock => LocalKeycode::CapsLock,
            Keycode::Tab => LocalKeycode::Tab,
            Keycode::Home => LocalKeycode::Home,
            Keycode::End => LocalKeycode::End,
            Keycode::PageUp => LocalKeycode::PageUp,
            Keycode::PageDown => LocalKeycode::PageDown,
            Keycode::Insert => LocalKeycode::Insert,
            Keycode::Delete => LocalKeycode::Delete,
            Keycode::Numpad0 => LocalKeycode::Numpad0,
            Keycode::Numpad1 => LocalKeycode::Numpad1,
            Keycode::Numpad2 => LocalKeycode::Numpad2,
            Keycode::Numpad3 => LocalKeycode::Numpad3,
            Keycode::Numpad4 => LocalKeycode::Numpad4,
            Keycode::Numpad5 => LocalKeycode::Numpad5,
            Keycode::Numpad6 => LocalKeycode::Numpad6,
            Keycode::Numpad7 => LocalKeycode::Numpad7,
            Keycode::Numpad8 => LocalKeycode::Numpad8,
            Keycode::Numpad9 => LocalKeycode::Numpad9,
            Keycode::NumpadSubtract => LocalKeycode::NumpadSubtract,
            Keycode::NumpadAdd => LocalKeycode::NumpadAdd,
            Keycode::NumpadDivide => LocalKeycode::NumpadDivide,
            Keycode::NumpadMultiply => LocalKeycode::NumpadMultiply,
            Keycode::NumpadEquals => LocalKeycode::NumpadEquals,
            Keycode::NumpadEnter => LocalKeycode::NumpadEnter,
            Keycode::NumpadDecimal => LocalKeycode::NumpadDecimal,
            Keycode::Grave => LocalKeycode::Grave,
            Keycode::Minus => LocalKeycode::Minus,
            Keycode::Equal => LocalKeycode::Equal,
            Keycode::LeftBracket => LocalKeycode::LeftBracket,
            Keycode::RightBracket => LocalKeycode::RightBracket,
            Keycode::BackSlash => LocalKeycode::BackSlash,
            Keycode::Semicolon => LocalKeycode::Semicolon,
            Keycode::Apostrophe => LocalKeycode::Apostrophe,
            Keycode::Comma => LocalKeycode::Comma,
            Keycode::Dot => LocalKeycode::Dot,
            Keycode::Slash => LocalKeycode::Slash,
        }
    }
}

pub trait VecInto<LocalKeycode> {
    fn vec_into(self) -> Vec<LocalKeycode>;
}

impl VecInto<LocalKeycode> for Vec<Keycode> {
    fn vec_into(self) -> Vec<LocalKeycode> {
        self.into_iter().map(std::convert::Into::into).collect()
    }
}

impl VecInto<LocalKeycode> for Vec<&Keycode> {
    fn vec_into(self) -> Vec<LocalKeycode> {
        self.into_iter().map(|item| item.clone().into()).collect()
    }
}