[workspace]
members = [ "app" ]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/Wasta-Geek/voice-of-hell.git"
authors = ["Corentin Ducatez <wasta.geek@gmail.com>"]

[workspace.dependencies]
