name: Testing backend
on:
  pull_request:
    paths: src-tauri
  push:
    paths: src-tauri
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo
        run: cargo fmt --check --manifest-path=src-tauri/Cargo.toml

  pre_test_build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=src-tauri/Cargo.toml
      - name: Cache cargo registry + build
        id: cache-cargo-save
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  linting:
    needs: pre_test_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=src-tauri/Cargo.toml

  testing:
    needs: pre_test_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=src-tauri/Cargo.toml
