name: Testing front
on:
  pull_request:
    paths: src
  push:
    paths: src
  workflow_dispatch:

jobs:
  pre_test_build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: source /home/voice-of-hell/.bashrc && pnpm install
        shell: bash -leo pipefail {0}
      - name: Cache cargo registry + build
        id: cache-cargo-save
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}

  linting:
    needs: pre_test_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Linting
        run: |
          source /home/voice-of-hell/.bashrc
          pnpm lint_js
        shell: bash -leo pipefail {0}

  testing:
    needs: pre_test_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Testing
        run: |
          source /home/voice-of-hell/.bashrc
          pnpm test_js
        shell: bash -leo pipefail {0}
