name: Testing front
on:
  pull_request:
    paths: src
  push:
    paths: src
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          source /home/voice-of-hell/.bashrc
          pnpm lint_js
        shell: bash

  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wasta-geek/voice_of_hell:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          source /home/voice-of-hell/.bashrc
          pnpm lint_js
        shell: bash
